name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: yarn install

    - name: Check Secrets
      run: echo "Checking secrets..."
      env:
        REACT_APP_AZURE_CLIENT_SECRET: ${{ secrets.REACT_APP_AZURE_CLIENT_SECRET }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

    - name: Validate Secrets (temporary)
      run: |
        if [ -z "${REACT_APP_AZURE_CLIENT_SECRET}" ]; then echo "REACT_APP_AZURE_CLIENT_SECRET is not set"; else echo "REACT_APP_AZURE_CLIENT_SECRET is set"; fi
        if [ -z "${SESSION_SECRET}" ]; then echo "SESSION_SECRET is not set"; else echo "SESSION_SECRET is set"; fi

    - name: Build project
      env:
        REACT_APP_AZURE_CLIENT_SECRET: ${{ secrets.REACT_APP_AZURE_CLIENT_SECRET }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      run: yarn run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
